import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const [bgColor, setBgColor] = useState("");
  const [click, setClick] = useState(false);

  const onClickHandler = () => {
    if (click) {
      setBgColor("");
    } else {
      setBgColor("white");
    }
    setClick(!click);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <div className={styles.plate}>Plate Setup</div>
        <div className={styles.setup}>
          <div className={styles.grid}>
            <div className={styles.grid_container}>
              <div className={styles.grid_child}>
                <div className={styles.accessN}></div>
                <button className={styles.access}>1</button>
                <button className={styles.access}>2</button>
                <button className={styles.access}>3</button>
                <button className={styles.access}>4</button>
                <button className={styles.access}>5</button>
                <button className={styles.access}>6</button>
                <button className={styles.access}>7</button>
                <button className={styles.access}>8</button>
                <button className={styles.access}>9</button>
                <button className={styles.access}>10</button>
                <button className={styles.access}>11</button>
                <button className={styles.access}>12</button>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>A</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>B</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>C</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>D</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>E</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>F</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>G</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
              <div className={styles.grid_child}>
                <button className={styles.accessY}>H</button>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
                <div
                  className={styles.access1}
                  style={{ backgroundColor: bgColor }}
                  onClick={onClickHandler}
                ></div>
              </div>
            </div>
          </div>
          <div className={styles.options}>1</div>
        </div>
      </div>
    </div>
  );
}

export default Home;
